//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public Sales(int id, int users, int product, int quantity, int total, DateTime? sale_date)
        {
            this.id = id;
            this.users = users;
            this.product = product;
            this.quantity = quantity;
            this.total = total;
            this.sale_date = sale_date;
        }
        public Sales() { }

        public int id { get; set; }
        public int users { get; set; }
        public int product { get; set; }
        public int quantity { get; set; }
        public int total { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
    
        public virtual User User { get; set; }
    }
}
